---
title: "day2b-exercises"
format: html
editor: visual
---

```{r}
# load tidyverse
library(tidyverse)

# creating function
eq1 <- function(x){
  3*x^2 + 4
}

#create values to evaluate function

my_data_range <- data.frame(x = c(1,100))

# plot as a continuous curve with geom_function

ggplot(data = my_data_range, aes(x = x)) + 
  geom_function(fun = eq1) # figures out y values from function we wrote with eq1
```

```{r}
ct <- function(t){
  t^3
}

# create data frame with range of values
my_data_range <- data.frame(t = c(-5,5))

# plot

ggplot(data = my_data_range, aes(x= t)) +
  geom_function(fun = ct)

# find derivative
dc_dt <- D(expr = expression(t^3), name = "t")
dc_dt

#store derivative as a function
dc_dt_fun <- function(t){
  3*t^2
}

ggplot(data = my_data_range, aes(x =t)) +
  geom_function(fun = ct, color = "red") +
  geom_function(fun = dc_dt_fun, color = "blue")

```

```{r}
# partial derivatives

#create expression
f_xyz <- expression(2*x*y-3*x^2*z^3)

# take partial with respect to x
df_dx <- D(expr = f_xyz, name = "x") #with respect to x

df_dy <- D(expr = f_xyz, name = "z") # with respect to Z


```
